[ZEPL-3858] add docs Logging Console
ZEPL/zepl-documentation pull request #58
Opened 2018-09-04 16:42 UTC by torreswoo

# What is this PR?
add docs Logging console
- [x] How to use logging console. & demo (.gif)
- [x] explain log messages

![image](https://user-images.githubusercontent.com/11022719/45044986-ad1ca800-b0ac-11e8-8d07-a5d51201b134.png)
![image](https://user-images.githubusercontent.com/11022719/45045043-d1788480-b0ac-11e8-88d1-6fa02671d77d.png)

2018-09-04 16:44 UTC, torreswoo commented
@sejunra I didnt write documentation much. i added some explanation about the log message. need some idea and comment. please help this.

2018-09-06 03:22 UTC, sejunra commented on docs/guide/logging_console.md
> +ZEPL supports logging console for Python, Spark and JDBC interpreter.
"... and JDBC interpreters." (plural)

2018-09-06 03:23 UTC, sejunra commented on docs/guide/logging_console.md
> +To begin using the Logging Console, simply the run the paragraph you're working on.
Remove "the" - "simply run the..."

2018-09-06 03:23 UTC, sejunra commented on docs/guide/logging_console.md
> +If you shutdown the notebook, Logging Console is automatically closed.
change "is automatically" to "will be automatically"

2018-09-06 03:25 UTC, sejunra commented on docs/guide/logging_console.md
> +After click `console` panel, start to get lastest logs from interpreter.
Change to "The Log Console is located at the bottom of the notebook. To open, click on the `Console` tab.

2018-09-06 03:27 UTC, sejunra commented on docs/guide/logging_console.md
> +A Logging Console that user can click from the notebook to show interpreter log and error output.
Change the whole sentence to "ZEPL provides a Log Console for a given notebook that the user can open to view the interpreter logs. The output stream in the Log Console will be specific to the given notebook and its interpreters.

2018-09-06 03:28 UTC, sejunra commented on docs/guide/logging_console.md
> +## How to use Logging Console
Change to "How to use the Log Console"

2018-09-06 03:31 UTC, sejunra commented on docs/guide/logging_console.md
> +<img src="../../img/logging_console_demo.gif" class="image-box big-img" />
Image should be replaced w/ one that shows the open log console with ideally a red error line as well.

2018-09-06 03:31 UTC, sejunra commented on docs/guide/logging_console.md
> +Checking Highlight `ERROR` log. you can get some cue. Also you are able to see processing log.
Let's remove this sentence.

2018-09-06 03:32 UTC, sejunra commented on docs/guide/logging_console.md
> +
ERROR logs are highlighted in red.

2018-09-06 03:33 UTC, sejunra commented on docs/guide/logging_console.md
> +* Notice : Logging Console is only activated in running notebook.
Change to "Note: You will only see log lines in the Log Console if the notebook is running."

2018-09-06 03:34 UTC, sejunra commented on docs/guide/logging_console.md
> +The interpreter logs is kind of [Apache Zeppelin Interpreter](https://zeppelin.apache.org/docs/0.8.0/usage/interpreter/overview.html) log.
Change to "The interpreter logs are based on the [Apache ..."

2018-09-06 03:35 UTC, sejunra commented on docs/guide/logging_console.md
> +This is sample Spark Interpreter log in Logging Console.
Change to "This is a sample Spark Interpreter log in the Log Console."

2018-09-06 03:36 UTC, sejunra commented on docs/guide/logging_console.md
> +# Logging Console in ZEPL
Change name to "Log Console"

2018-09-06 03:36 UTC, sejunra requested changes
grammar changes and let's keep the name of it to "Log Console". That's what I thought it was.

2018-09-06 12:56 UTC, torreswoo commented
@sejunra Thanks for your comments. i resolve these. help review it.

2018-09-07 05:59 UTC, sejunra commented on docs/guide/logging_console.md
> +To begin using the Logging Console, simply run the paragraph you're working on.
change "Logging Console" to "Log Console"

2018-09-07 06:00 UTC, sejunra commented on docs/guide/logging_console.md
> +If you shutdown the notebook, Logging Console will be automatically closed.
change "Logging Console" to "Log Console"

2018-09-07 06:01 UTC, sejunra requested changes
a couple of mentions of "Logging Console". Please change to "Log Console". And please change the image that shows the whole log console in line 14. Thx.

2018-09-09 17:36 UTC, torreswoo commented
@sejunra Thanks i resolve it again.

2018-09-10 04:03 UTC, sravan-s reviewed
Shouldn't we mention that log console isn't available for normal customers?

2018-09-10 04:05 UTC, torreswoo commented
@sravan-s i move the log console category into enterprise section.

2018-09-10 19:16 UTC, sejunra approved these changes

2018-09-11 05:04 UTC, merged